;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Çar Kas 11 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
      MOV AL, 90H
      OUT 46H, AL
ENDLESS:
     IN AL, 40H 
     TEST AL, 80H
     JZ bolme
     AND AL, 0FH
     SHL AL, 1
     JMP devam
bolme:
     AND AL, 0FH
     SHR AL, 1
devam:
     OUT 42H, AL
        JMP ENDLESS
CODE    ENDS
        END START